### ISSUE TITLE
Failed to setup account

### ISSUE THREAD

**Issue by r3pek** [tuya/tuya-smart-life#20]
Account was added successfully but when starting up, it fails to setup the account and no devices are shown.

 This is the error log contents:
```
2023-11-05 23:02:32.550 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry r3pek@nospam.r3pek.org for smartlife
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartlife/__init__.py", line 72, in async_setup_entry
    await hass.async_add_executor_job(smart_life_manager.update_device_cache)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tuya_sharing/manager.py", line 62, in update_device_cache
    devices_by_home = self.device_repository.query_devices_by_home(home.id)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tuya_sharing/device.py", line 106, in query_devices_by_home
    return self._query_devices(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tuya_sharing/device.py", line 125, in _query_devices
    self.update_device_strategy_info(device)
  File "/usr/local/lib/python3.11/site-packages/tuya_sharing/device.py", line 160, in update_device_strategy_info
    dp_id_map[dp_status_relation["dpId"]] = {
              ~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'dpId'
```

**Comment by shihuimiao** [comment]
Please reload again, Check if there are any further issues

**Comment by r3pek** [comment]
Fixed. Did I make anything wrong on the account setup?

**Comment by shihuimiao** [comment]
Check if the field 'online' in the diagnostics file is true, This prompt will appear when the device is offline

**Comment by shihuimiao** [comment]
> Just FYI, since I don't know if it's related, the AC displays a message saying that "This entity is no longer being provided by the smartlife integration. If the entity is no longer in use, delete it in settings." but it does clearly work on the app...

Interface return value type error fixed, please reload the smartlife integration try again.
