### ISSUE TITLE
Climate fails to initialize

### ISSUE THREAD

**Issue by webfrea-k** [tuya/tuya-smart-life#22]
IR Heater fails to initialize with the below stack trace.

I've managed to get it working by changing the scale_value function in base.py to:
```
   def scale_value(self, value: float | int) -> float:
        """Scale a value."""
        if self.scale is None:
            self.scale = 0.0  # Set a default scale of 0.0 if self.scale is None
        value = float(value)  # Ensure the input value is treated as a float
        return value / (10 ** self.scale)
```

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 786, in _async_generate_attributes
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 323, in state_attributes
    self.target_temperature,
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartlife/climate.py", line 401, in target_temperature
    return self._set_temperature.scale_value(temperature)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartlife/base.py", line 49, in scale_value
    return value / (10 ** self.scale)
           ~~~~~~^~~~~~~~~~~~~~~~~~~~
```

**Comment by shihuimiao** [comment]
Detected whether it is None in the climate.py file
if it is newly added device, You can enable the debug log to check whether the received data is correct. Previously, i fixed the topic bug of the mqtt receiving data type, you can pull the latest code, reinstall again.

**Comment by webfrea-k** [comment]
Hi @shihuimiao , I have the latest code installed via HACS. Or should I do anything different?

**Comment by shihuimiao** [comment]
Interface return value type error fixed, please reload the smartlife integration try again.

**Comment by webfrea-k** [comment]
Seems to work ok now. Tnx!
