### ISSUE TITLE
expired token error

### ISSUE THREAD

**Issue by vtolstov** [tuya/tuya-smart-life#80]
tuya_api.async_get_devices_list()

[2024-01-09 08:08:15,964] [customer-customerapi] net work error = network error:(1010) token is expired
2024-01-09 08:08:15.964 ERROR (SyncWorker_3) [tuya_sharing] net work error = network error:(1010) token is expired
2024-01-09 08:08:16.010 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry home@selfip.ru for smartlife
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartlife/__init__.py", line 69, in async_setup_entry
    await hass.async_add_executor_job(smart_life_manager.report_version, __version__, smart_life_version, sharing_sdk)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tuya_sharing/manager.py", line 69, in report_version
    self.user_repository.user_version_report(ha_version, integration_version, sdk_version)
  File "/usr/local/lib/python3.11/site-packages/tuya_sharing/user.py", line 46, in user_version_report
    self.api.post("/v1.0/m/life/home-assistant/qrcode/versions", None, {
  File "/usr/local/lib/python3.11/site-packages/tuya_sharing/customerapi.py", line 192, in post
    return self.__request("POST", path, params, body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tuya_sharing/customerapi.py", line 121, in __request
    raise Exception(f"network error:({ret['code']}) {ret['msg']}")
Exception: network error:(-9999999) sign invalid

**Comment by shihuimiao** [comment]
Cloud interface call failed, try reload integration

**Comment by vtolstov** [comment]
in home assistant this is not possible extension not loaded with this error

**Comment by vtolstov** [comment]
hm... may be this is time to go next with tuyalocal

**Comment by gateriderz** [comment]
I get the same issue while activating tuya scenes.

```

2024-01-16 07:00:01.278 ERROR (MainThread) [homeassistant.components.automation.garagelightsreset] While executing automation automation.garagelightsreset
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 669, in async_trigger
    await self.action_script.async_run(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1587, in async_run
    return await asyncio.shield(run.async_run())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 426, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 479, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 502, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 713, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 675, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 882, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/scene/__init__.py", line 114, in _async_activate
    await self.async_activate(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/scene/__init__.py", line 135, in async_activate
    await task
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartlife/scene.py", line 63, in activate
    self.home_manager.trigger_scene(self.scene.home_id, self.scene.scene_id)
  File "/usr/local/lib/python3.11/site-packages/tuya_sharing/manager.py", line 122, in trigger_scene
    self.scene_repository.trigger_scene(home_id, scene_id)
  File "/usr/local/lib/python3.11/site-packages/tuya_sharing/scenes.py", line 42, in trigger_scene
    response = self.api.post("/v1.0/m/scene/ha/trigger", None, {"homeId": home_id, "sceneId": scene_id})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tuya_sharing/customerapi.py", line 192, in post
    return self.__request("POST", path, params, body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tuya_sharing/customerapi.py", line 121, in __request
    raise Exception(f"network error:({ret['code']}) {ret['msg']}")
Exception: network error:(-9999999) sign invalid

```

**Comment by vtolstov** [comment]
i get this error again
```
[2024-01-17 07:03:52,267] [customer-customerapi] net work error = network error:(1010) token is expired
2024-01-17 07:03:52.267 ERROR (SyncWorker_41) [tuya_sharing] net work error = network error:(1010) token is expired
2024-01-17 07:03:52.313 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry home@selfip.ru for smartlife
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartlife/__init__.py", line 69, in async_setup_entry
    await hass.async_add_executor_job(smart_life_manager.report_version, __version__, smart_life_version, sharing_sdk)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tuya_sharing/manager.py", line 69, in report_version
    self.user_repository.user_version_report(ha_version, integration_version, sdk_version)
  File "/usr/local/lib/python3.11/site-packages/tuya_sharing/user.py", line 46, in user_version_report
    self.api.post("/v1.0/m/life/home-assistant/qrcode/versions", None, {
  File "/usr/local/lib/python3.11/site-packages/tuya_sharing/customerapi.py", line 192, in post
    return self.__request("POST", path, params, body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tuya_sharing/customerapi.py", line 121, in __request
    raise Exception(f"network error:({ret['code']}) {ret['msg']}")
Exception: network error:(-9999999) sign invalid
```
