### ISSUE TITLE
Failed to setup error

### ISSUE THREAD

**Issue by ivik** [tuya/tuya-smart-life#91]
# The problem
After a backup restore I see there is an issue with this integration, its seems to hub is missing. I add a hub again and all devices are working but still the an error is displayed in the integration page. 
## Your Environment
Home Assistant Green, everything up 2 date.

Include as many relevant details about the environment you experienced the bug in

* tuya-device-sharing-sdk Version used: tuya-device-sharing-sdk==0.1.9
* Device diagnostic file:

## Current Behavior

From log: 

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartlife/__init__.py", line 69, in async_setup_entry
    await hass.async_add_executor_job(smart_life_manager.report_version, __version__, smart_life_version, sharing_sdk)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tuya_sharing/manager.py", line 69, in report_version
    self.user_repository.user_version_report(ha_version, integration_version, sdk_version)
  File "/usr/local/lib/python3.11/site-packages/tuya_sharing/user.py", line 46, in user_version_report
    self.api.post("/v1.0/m/life/home-assistant/qrcode/versions", None, {
  File "/usr/local/lib/python3.11/site-packages/tuya_sharing/customerapi.py", line 192, in post
    return self.__request("POST", path, params, body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tuya_sharing/customerapi.py", line 121, in __request
    raise Exception(f"network error:({ret['code']}) {ret['msg']}")
Exception: network error:(-9999999) sign invalid

**Comment by shihuimiao** [comment]
Try deleting the integration and scanning the code again to log in. This error is due to an invalid interface signature, which may be due to an issue with your token.
